### ISSUE TITLE
NN GUI alpha test

### ISSUE THREAD

**Issue by c-yuwei** [braph-software/BRAPH-2#1311]
This issue aims to collect the suggestions/bugs via internal test (i.e. tested by users in the group).

Please test the NN GUI with branch _yc-NN-alpha-test_ (https://github.com/softmatterlab/BRAPH-2-Matlab/tree/yc-NN-alpha-testing)

Please report the suggestions/bugs in other issues, I will solve them.
To track the progress, please mark the checkbox below after you finish that single pipeline. 

Available NN GUI pipelines are

- [ ] CON Classification
`file: braph2genesis\pipelines\connectivity NN\pipeline_neural_networks_classification_con_wu.braph2`
- [ ] CON Classification Cross-Validation
`file: braph2genesis\pipelines\connectivity NN\pipeline_neural_networks_classification_cross_validation_con_wu.braph2`
- [ ] FUN Regression
`file: braph2genesis\pipelines\functional NN\pipeline_neural_networks_regression_fun_wu.braph2`
- [ ] FUN Regression Cross-Validation
`file: braph2genesis\pipelines\functional NN\pipeline_neural_networks_regression_cross_validation_fun_wu.braph2`
- [ ] CON-FUN MP Classification
`file: braph2genesis\pipelines\connectivity-functional multiplex NN\pipeline_neural_networks_classification_con_fun_mp_wu.braph2`
- [ ] ST Classification
`file: braph2genesis\pipelines\structural NN\pipeline_neural_networks_classification_st.braph2`

**Comment by annacanal** [comment]
CON classification, when pressing "Set Measures":

```
Error using containers.Map/subsasgn
Specified key type does not match the type expected for this container.

Error in subclasses (line 77)
    hashtable(hash) = subclass_list;

Error in subclasses (line 64)
            list_subclasses_in_subdirectory = subclasses(class_name, [directory filesep subdirectories(i).name], true);

Error in Format>@(x)any(strcmp(x,subclasses(class,[],[],true))) (line 579)
                        all(cellfun(@(x) any(strcmp(x, subclasses(class, [], [], true))), value));

Error in Format.checkFormat (line 579)
                        all(cellfun(@(x) any(strcmp(x, subclasses(class, [], [], true))), value));

Error in NNData.checkProp (line 838)
					check = Format.checkFormat(Format.CLASSLIST, value, NNData.getPropSettings(prop));

Error in NNData_CON_WU.checkProp (line 676)
					check = checkProp@NNData(prop, value);

Error in Element/set (line 720)
                                    el.checkProp(prop, value) % check value format

Error in PPNNData_Measures/cb_set_measures (line 942)
		    el.set('Measures', measure_short_list);

Error in PPNNData_Measures/draw/cb_measure_btn (line 817)
		        pr.cb_set_measures()
 
Error while evaluating UIControl Callback.
```

**Comment by annacanal** [comment]
CON classification, error during training when using adjacency matrices:
```
Error using nnet.internal.cnn.onnx.importONNXNetwork>iValidateInputs (line 129)
'InputDataFormats' is not a recognized parameter. For a list of valid name-value pair arguments, see the documentation for this function.

Error in nnet.internal.cnn.onnx.importONNXNetwork (line 5)
[Filename, OutputLayerType, UserImageInputSize, Classes] = iValidateInputs(filename, varargin{:});

Error in importONNXNetwork (line 52)
Network = nnet.internal.cnn.onnx.importONNXNetwork(modelfile, varargin{:});

Error in NNBase/to_net (line 866)
		        net = importONNXNetwork(filename, "InputDataFormats", format, "OutputLayerType", type, "Classes", class_name);

Error in NNClassifierDNN/to_net (line 1031)
		    net = to_net@NNBase(nn, saved_nn, nn.get('INPUT_FORMAT'), "classification", classes);

Error in PPNNBase_Model/draw/cb_button_mod_calc (line 785)
		        net = el.to_net(el.get('MODEL'));
 
Error while evaluating UIControl Callback.
```

**Comment by annacanal** [comment]
Same problem in Functional regression (so i guess the same on the other NN pipelines):
```
Error using nnet.internal.cnn.onnx.importONNXNetwork>iValidateInputs (line 129)
'InputDataFormats' is not a recognized parameter. For a list of valid name-value pair arguments, see the documentation for this function.

Error in nnet.internal.cnn.onnx.importONNXNetwork (line 5)
[Filename, OutputLayerType, UserImageInputSize, Classes] = iValidateInputs(filename, varargin{:});

Error in importONNXNetwork (line 52)
Network = nnet.internal.cnn.onnx.importONNXNetwork(modelfile, varargin{:});

Error in NNBase/to_net (line 870)
		        net = importONNXNetwork(filename, "InputDataFormats", format, "OutputLayerType", type);

Error in NNRegressorDNN/to_net (line 1027)
		    net = to_net@NNBase(nn, saved_nn, nn.get('INPUT_FORMAT'), "regression");

Error in PPNNBase_Model/draw/cb_button_mod_calc (line 785)
		        net = el.to_net(el.get('MODEL'));
 
Error while evaluating UIControl Callback.
```

**Comment by c-yuwei** [comment]
> CON classification, when pressing "Set Measures":
> 
> ```
> Error using containers.Map/subsasgn
> Specified key type does not match the type expected for this container.
> 
> Error in subclasses (line 77)
>     hashtable(hash) = subclass_list;
> 
> Error in subclasses (line 64)
>             list_subclasses_in_subdirectory = subclasses(class_name, [directory filesep subdirectories(i).name], true);
> 
> Error in Format>@(x)any(strcmp(x,subclasses(class,[],[],true))) (line 579)
>                         all(cellfun(@(x) any(strcmp(x, subclasses(class, [], [], true))), value));
> 
> Error in Format.checkFormat (line 579)
>                         all(cellfun(@(x) any(strcmp(x, subclasses(class, [], [], true))), value));
> 
> Error in NNData.checkProp (line 838)
> 					check = Format.checkFormat(Format.CLASSLIST, value, NNData.getPropSettings(prop));
> 
> Error in NNData_CON_WU.checkProp (line 676)
> 					check = checkProp@NNData(prop, value);
> 
> Error in Element/set (line 720)
>                                     el.checkProp(prop, value) % check value format
> 
> Error in PPNNData_Measures/cb_set_measures (line 942)
> 		    el.set('Measures', measure_short_list);
> 
> Error in PPNNData_Measures/draw/cb_measure_btn (line 817)
> 		        pr.cb_set_measures()
>  
> Error while evaluating UIControl Callback.
> ```

This one is solved by https://github.com/softmatterlab/BRAPH-2-Matlab/pull/1320

**Comment by c-yuwei** [comment]
> Same problem in Functional regression (so i guess the same on the other NN pipelines):
> 
> ```
> Error using nnet.internal.cnn.onnx.importONNXNetwork>iValidateInputs (line 129)
> 'InputDataFormats' is not a recognized parameter. For a list of valid name-value pair arguments, see the documentation for this function.
> 
> Error in nnet.internal.cnn.onnx.importONNXNetwork (line 5)
> [Filename, OutputLayerType, UserImageInputSize, Classes] = iValidateInputs(filename, varargin{:});
> 
> Error in importONNXNetwork (line 52)
> Network = nnet.internal.cnn.onnx.importONNXNetwork(modelfile, varargin{:});
> 
> Error in NNBase/to_net (line 870)
> 		        net = importONNXNetwork(filename, "InputDataFormats", format, "OutputLayerType", type);
> 
> Error in NNRegressorDNN/to_net (line 1027)
> 		    net = to_net@NNBase(nn, saved_nn, nn.get('INPUT_FORMAT'), "regression");
> 
> Error in PPNNBase_Model/draw/cb_button_mod_calc (line 785)
> 		        net = el.to_net(el.get('MODEL'));
>  
> Error while evaluating UIControl Callback.
> ```

Yes it was everywhere, and it is solved by https://github.com/softmatterlab/BRAPH-2-Matlab/pull/1320
